packages:
  - frontend
  - backend

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@prisma/client'
  - '@prisma/engines'
  - bcrypt
  - electron
  - esbuild
  - mediasoup
  - prisma
  - protobufjs
